# Hyprland configuration overrides

# 1. (Optional, but good practice) Redefine the $terminal variable
$terminal = uwsm app -- ghostty

# 2. Redefine the keybinding to explicitly use the home directory (~)
unbind = SUPER, RETURN
bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory=~

# Monitor 1: Dell S2417DG (1440p) - This is the Right Monitor.
# Position starts at 2887 pixels (3840 / 1.33 ≈ 2887)
monitor=DP-1,2560x1440@59.95100,2887x0,1

# Monitor 2: DELL U2720Q (4K) - This is the Left Monitor, starting at 0x0.
monitor=DP-2,3840x2160@59.99700,0x0,1.33

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5
    dim_inactive = false
}
